#!/usr/bin/env bash

set -e

cargo build --release --bin cosmic-accent --bin launch-color
last_accent=""
while sleep 1
do
    accent="$(target/release/cosmic-accent)"
    if [ "${accent}" != "${last_accent}" ]
    then
        sudo target/release/launch-color ${accent}
    fi
    last_accent="${accent}"
done
